config/routes.rb
Rails.application.routes.draw do
  resources :invoice_details
  resources :invoice_headers
  resources :invoice_states
  resources :products
  resources :customers
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice_state.rb
class InvoiceState < ApplicationRecord
    self.table_name = 'InvoiceState'
end

app/controllers/invoice_states_controller.rb
class InvoiceStatesController < ApplicationController
  before_action :set_invoice_state, only: [:show, :edit, :update, :destroy]

  # GET /invoice_states
  # GET /invoice_states.json
  def index
    @invoice_states = InvoiceState.all
  end

  # GET /invoice_states/1
  # GET /invoice_states/1.json
  def show
  end

  # GET /invoice_states/new
  def new
    @invoice_state = InvoiceState.new
  end

  # GET /invoice_states/1/edit
  def edit
  end

  # POST /invoice_states
  # POST /invoice_states.json
  def create
    @invoice_state = InvoiceState.new(invoice_state_params)

    respond_to do |format|
      if @invoice_state.save
        format.html { redirect_to @invoice_state, notice: 'Invoice state was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_state }
      else
        format.html { render :new }
        format.json { render json: @invoice_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_states/1
  # PATCH/PUT /invoice_states/1.json
  def update
    respond_to do |format|
      if @invoice_state.update(invoice_state_params)
        format.html { redirect_to @invoice_state, notice: 'Invoice state was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_state }
      else
        format.html { render :edit }
        format.json { render json: @invoice_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_states/1
  # DELETE /invoice_states/1.json
  def destroy
    @invoice_state.destroy
    respond_to do |format|
      format.html { redirect_to invoice_states_url, notice: 'Invoice state was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_state
      @invoice_state = InvoiceState.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_state_params
      params.require(:invoice_state).permit(:Name)
    end
end

app/helpers/invoice_states_helper.rb
module InvoiceStatesHelper
end

app/views/invoice_states/_form.html.erb
<%= form_with(model: invoice_state, local: true) do |form| %>
  <% if invoice_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice_state.errors.count, "error") %> prohibited this invoice_state from being saved:</h2>

      <ul>
      <% invoice_state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoice_states/edit.html.erb
<h1>Editing Invoice State</h1>

<%= render 'form', invoice_state: @invoice_state %>

<%= link_to 'Show', @invoice_state %> |
<%= link_to 'Back', invoice_states_path %>

app/views/invoice_states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoice States</h1>

<div class="new"><%= link_to 'New', new_invoice_state_path %></div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @invoice_states.each do |invoice_state| %>
      <tr>
        <td><%= invoice_state.Name %></td>
        <td><%= link_to 'Show', invoice_state %></td>
        <td><%= link_to 'Edit', edit_invoice_state_path(invoice_state) %></td>
        <td><%= link_to 'Destroy', invoice_state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "Home", root_path %>

app/views/invoice_states/new.html.erb
<h1>New Invoice State</h1>

<%= render 'form', invoice_state: @invoice_state %>

<%= link_to 'Back', invoice_states_path %>

app/views/invoice_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @invoice_state.Name %>
</p>

<%= link_to 'Edit', edit_invoice_state_path(@invoice_state) %> |
<%= link_to 'Back', invoice_states_path %>