config/routes.rb
Rails.application.routes.draw do
  resources :invoice_details
  resources :invoice_headers
  resources :invoice_states
  resources :products
  resources :customers
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
    self.table_name = 'InvoiceDetail'
end

app/controllers/invoice_details_controller.rb
class InvoiceDetailsController < ApplicationController
  before_action :set_invoice_detail, only: [:show, :edit, :update, :destroy]

  # GET /invoice_details
  # GET /invoice_details.json
  def index
    @invoice_details = InvoiceDetail.all
  end

  # GET /invoice_details/1
  # GET /invoice_details/1.json
  def show
  end

  # GET /invoice_details/new
  def new
    @invoice_detail = InvoiceDetail.new
  end

  # GET /invoice_details/1/edit
  def edit
  end

  # POST /invoice_details
  # POST /invoice_details.json
  def create
    @invoice_detail = InvoiceDetail.new(invoice_detail_params)

    respond_to do |format|
      if @invoice_detail.save
        format.html { redirect_to @invoice_detail, notice: 'Invoice detail was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_detail }
      else
        format.html { render :new }
        format.json { render json: @invoice_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_details/1
  # PATCH/PUT /invoice_details/1.json
  def update
    respond_to do |format|
      if @invoice_detail.update(invoice_detail_params)
        format.html { redirect_to @invoice_detail, notice: 'Invoice detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_detail }
      else
        format.html { render :edit }
        format.json { render json: @invoice_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_details/1
  # DELETE /invoice_details/1.json
  def destroy
    @invoice_detail.destroy
    respond_to do |format|
      format.html { redirect_to invoice_details_url, notice: 'Invoice detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_detail
      @invoice_detail = InvoiceDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_detail_params
      params.require(:invoice_detail).permit(:Header, :Product, :Quantity, :Price)
    end
end

app/helpers/invoice_details_helper.rb
module InvoiceDetailsHelper
end

app/views/invoice_details/_form.html.erb
<%= form_with(model: invoice_detail, local: true) do |form| %>
  <% if invoice_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice_detail.errors.count, "error") %> prohibited this invoice_detail from being saved:</h2>

      <ul>
      <% invoice_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Header %>
    <%= form.text_field :Header %>
  </div>

  <div class="field">
    <%= form.label :Product %>
    <%= form.number_field :Product %>
  </div>

  <div class="field">
    <%= form.label :Quantity %>
    <%= form.number_field :Quantity %>
  </div>

  <div class="field">
    <%= form.label :Price %>
    <%= form.text_field :Price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoice_details/edit.html.erb
<h1>Editing Invoice Detail</h1>

<%= render 'form', invoice_detail: @invoice_detail %>

<%= link_to 'Show', @invoice_detail %> |
<%= link_to 'Back', invoice_details_path %>

app/views/invoice_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoice Details</h1>

<table>
  <thead>
    <tr>
      <th>Header</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_details.each do |invoice_detail| %>
      <tr>
        <td><%= invoice_detail.Header %></td>
        <td><%= invoice_detail.Product %></td>
        <td><%= invoice_detail.Quantity %></td>
        <td><%= invoice_detail.Price %></td>
        <td><%= link_to 'Show', invoice_detail %></td>
        <td><%= link_to 'Edit', edit_invoice_detail_path(invoice_detail) %></td>
        <td><%= link_to 'Destroy', invoice_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "Home", root_path %>

app/views/invoice_details/new.html.erb
<h1>New Invoice Detail</h1>

<%= render 'form', invoice_detail: @invoice_detail %>

<%= link_to 'Back', invoice_details_path %>

app/views/invoice_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Header:</strong>
  <%= @invoice_detail.Header %>
</p>

<p>
  <strong>Product:</strong>
  <%= @invoice_detail.Product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @invoice_detail.Quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @invoice_detail.Price %>
</p>

<%= link_to 'Edit', edit_invoice_detail_path(@invoice_detail) %> |
<%= link_to 'Back', invoice_details_path %>